### ISSUE TITLE
Support for fully qualified table names

### ISSUE THREAD

**Issue by pnomolos** [seamusabshere/upsert#101]
This has come up before in #53 and is partially fixed in #95.

### Requested Support

- MySQL: Generally (appears) to not be an issue, probably due to it only the edge-case of wanting to upsert to a different database - you'd generally use the connection for the other database instead.  That being said, we might as well add support for `dbname.tablename` for those using MySQL.  We *will* have to make sure that our changes don't cause any regressions :)
- Postgres: As noted in #53 and #95, the demand is there for this.  I also have an internal patch to support this (with Sequel).
- MSSQL: Once MSSQL support is running (I'm hoping sometime this year ... maybe?).  The demand will likely also be there.  See https://technet.microsoft.com/en-us/library/ms187879(v=sql.105).aspx for further information.
- Sqlite3: Use-case would be uncommon, but similar to MySQL - via the [ATTACH](http://sqlite.org/lang_attach.html) keyword.
- Others: We'll likely want to handle those as they occur.  I believe most other larger DBs support db/schema name qualification.

### Syntax

The general syntax for referring to an alternative database/schema is `db_or_schema.table_name`.  However, a period is valid inside a quoted identifier, so passing Just "db.some_table" into Upsert isn't a valid option, as that could equally be a valid database __or__ table name. `"data.base.name"."table.name"` is valid in Postgres 🙄 

I propose that we use an array of String-ish objects to refer to something that's qualified beyond just the table name.  `["database", "table"]` and `[:database, :table]` should both be valid.  Thoughts on just doing `database_object.map(&:to_s)` in general so you can pass anything responding to `to_s`?

### Caveats

1. In playing around with this, it occurred to me that the Postgres Upsert adapter won't work with a fully qualified name (Because it looks up the name as a string, as opposed to an oid).  I imagine there will be other similar edge-cases, so care will need to be taken that we cover all of those.
2. In Postgres (at the very least) quoting an identifier causes it to also be case-sensitive (ref. the note at the very bottom of [4.1.1](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)).  This has the potential to be an issue for people upgrading - if we start fully quoting everything then there rises the possibility that applications assuming case-insensitivity no longer work properly.  With that in mind, should we consider the inclusion of this to also push Upsert to v3.0?

### Other

This would need to be done before #100 could be properly supported.

/cc @seamusabshere @devonestes @zakcrawford

**Comment by zakcrawford** [comment]
I think that people relying on case insensitivity should not be an issue for pushing this in a new major version.
A major version bump is the place to make 'breaking' changes.
