### ISSUE TITLE
Postgres String[] values are escaped unnecessarily

### ISSUE THREAD

**Issue by searls** [seamusabshere/upsert#120]
Here's a simple test program:

```ruby
#!/usr/bin/env ruby

require_relative "config/environment"

Upsert.batch(Item.connection.raw_connection, :items) do |upsert|
  upsert.row({id: 1}, {
    strings: %w[don't can't won't],
  })
end

puts "array: #{Item.find(1).strings}"
```

This will print: `array: ["don''t", "can''t", "won''t", "lol''"]`

**Comment by pnomolos** [comment]
@searls Looks good (and looks like tests are passing).  Do you mind writing a test case for this (that previous failed, and is now passing)?

**Comment by searls** [comment]
I'm sorry, I took a stab at this but I couldn't get the gem to build locally try as I might because of the mysql2 gem failing to build on my machine :(

**Comment by pnomolos** [comment]
@searls No problem!  I'll get a spec together :)
