### ISSUE TITLE
Maybe a concurrency Issue?

### ISSUE THREAD

**Issue by RaresSalcudean** [seamusabshere/upsert#123]
Hello,

Currently, I have a migration script that uses upsert to update 4 million records in batches of 30,000. I have multiple Resque Workers for each batch so ~134 workers each executing one batch.

From time to time I get the following error (full output):

```
{"failed_at"=>"2019/08/24 07:40:17 UTC", "payload"=>{"class"=>"ImportWorker", "args"=>["0cf319c2ab8bf20a115db0eb835e7879", {"worker"=>"GolfServicesV2", "start"=>0, "finish"=>30000, "params"=>{"gender"=>nil, "queue"=>1}}]}, "exception"=>"PG::UniqueViolation", "error"=>"ERROR:  duplicate key value violates unique constraint \"pg_proc_proname_args_nsp_index\"\nDETAIL:  Key (proname, proargtypes, pronamespace)=(upsert2_2_1_golfer_clubs_sel_id_set_club_id_a_club_id2635252304, 20 20 20 1043 20 20 20 1043 1043 1043 1043 1043, 2200) already exists.\n", "backtrace"=>["/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert/connection/PG_Connection.rb:13:in `async_exec'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert/connection/PG_Connection.rb:13:in `execute'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert/merge_function/postgresql.rb:258:in `create!'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert/merge_function/postgresql.rb:76:in `rescue in pg_function'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert/merge_function/postgresql.rb:68:in `pg_function'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert/merge_function/postgresql.rb:53:in `execute'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert.rb:219:in `row'", "/home/ubuntu/workspace/whs/app/lib/scripts/import/golf_services_v2.rb:54:in `block (2 levels) in start_import'", "/home/ubuntu/workspace/whs/app/lib/scripts/import/golf_services_v2.rb:26:in `each'", "/home/ubuntu/workspace/whs/app/lib/scripts/import/golf_services_v2.rb:26:in `block in start_import'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/gems/upsert-2.2.1/lib/upsert.rb:73:in `batch'", "/home/ubuntu/workspace/whs/app/lib/scripts/import/golf_services_v2.rb:25:in `start_import'", "/home/ubuntu/workspace/whs/app/lib/scripts/import/golf_services_v2.rb:5:in `run'", "/home/ubuntu/workspace/whs/app/worker/import_worker.rb:16:in `block in perform'", "/home/ubuntu/workspace/whs/config/initializers/db_2_deprecation_warning.rb:7:in `suppress_warnings'", "/home/ubuntu/workspace/whs/app/worker/import_worker.rb:10:in `perform'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/bundler/gems/resque-status-1a2bafb405f3/lib/resque/plugins/status.rb:161:in `safe_perform!'", "/home/ubuntu/.rvm/gems/ruby-2.5.4@whs_v51/bundler/gems/resque-status-1a2bafb405f3/lib/resque/plugins/status.rb:137:in `perform'"], "worker"=>"ip-172-31-83-242:3872:*", "queue"=>"statused"}
```

The main issue:

```
"exception"=>"PG::UniqueViolation", "error"=>"ERROR:  duplicate key value violates unique constraint \"pg_proc_proname_args_nsp_index\"\nDETAIL:  Key (proname, proargtypes, pronamespace)=(upsert2_2_1_golfer_clubs_sel_id_set_club_id_a_club_id2635252304, 20 20 20 1043 20 20 20 1043 1043 1043 1043 1043, 2200) already exists.\n"
```

I'm not 100% sure why it triggers the duplicate key unique constraint, for the simple fact that all the time when I re-run this failed job it works. From all the ids present, I'm not sure which one is the actual row ID that the upsert is performed on.

My guess is that it is a concurrency issue related to the Lock / Write from PostgreSQL.

E.g., my RDS DB sessions are off the chart when this upsert script is running on 134 workers.

<img width="331" alt="Screenshot 2019-08-24 at 10 42 00" src="https://user-images.githubusercontent.com/29229646/63634747-5284af00-c663-11e9-8c0c-06cb1122f4cc.png">

Any tips on debugging this issue will be very helpful.

Thank you very much and have a great day!

**Comment by pnomolos** [comment]
Hi @RaresSalcudean can you share a little more about your setup such as PG version, and if possible what your table schema looks like and some sample data?

If it’s possible for you to use at least PG 9.6 and change your schema to untilize the new native UPSERT ability that might help out your performance as well :)

**Comment by RaresSalcudean** [comment]
@pnomolos I am using PG 11 doe...

**Comment by RaresSalcudean** [comment]
I believe 100% it was a concurrency Issue, right at the start when the jobs start using Upsert, they do the check if the upsert function exists if not create it. My gut tells me that 2 jobs tried creating the function at the same time this failed.

I fixed the issue by doing a 'fake' upsert in sync before the jobs start, so the functions are created.

Have a great day!
Rares
