### ISSUE TITLE
Have you considered using a common table expression?

### ISSUE THREAD

**Issue by timuckun** [seamusabshere/upsert#14]
http://stackoverflow.com/questions/7802806/bulk-upsert-with-ruby-on-rails

WITH updates (id) AS (
     UPDATE mytable SET .....
      WHERE ....
     RETURNING id
)
INSERT INTO mytable (....)
SELECT ... 
  FROM mytemptable
 WHERE id NOT IN (select id from updates);

**Comment by pnomolos** [comment]
From everything I've read it seems like writeable CTEs, while likely faster, don't 100% guarantee correctness (unlike the function, which will).

- http://dba.stackexchange.com/questions/78510/why-is-cte-open-to-lost-updates (This one, in particular)
- http://stackoverflow.com/questions/17267417/how-to-upsert-merge-insert-on-duplicate-update-in-postgresql/17267423#17267423
- http://stackoverflow.com/questions/1109061/insert-on-duplicate-update-in-postgresql
- https://www.depesz.com/2012/06/10/why-is-upsert-so-complicated/

**Comment by pnomolos** [comment]
I'm going to close this for the time being, now that Postgres provides native upsert and we use that when available.
