### ISSUE TITLE
Getting PG Error from specs

### ISSUE THREAD

**Issue by aaudette** [seamusabshere/upsert#23]
I have the following method using upsert:
def job_code
    @code = JobCode.new(params[:api])
    selector = {:store_id => @code.store_id, :source_id => @code.source_id}
    setter = { :name => @code.name, :created_at => Time.now, :updated_at => Time.now }
    JobCode.upsert(selector, setter)
    render_json(@code, :created)
  end

And here is the spec that is giving me trouble:
describe 'job_code' do
    context 'when it is a new job_code' do
      Given(:params) {  {:format => 'json', :api=>{ :store_id=> 1, :source_id=>25, :name=>'Server'}} }
      Then { lambda{ post :job_code, params }.should change(JobCode, :count) }
    end

```
context 'when the item already exists' do
  Given!(:code) { FactoryGirl.create :job_code }
  Given(:params) {  {:format => 'json', :api=>{ :store_id=> code.store_id, :source_id=>code.source_id, :name=>code.name}} }
  Then { lambda{ post :job_code, params }.should_not change(JobCode, :count) }   
end
```

  end

I can run each of these specs individually and everything works well, but when I run them together, I get the following error:

1) ApiController job_code when the item already exists 
     Failure/Error: Then { lambda{ post :job_code, params }.should_not change(JobCode, :count) }
     PG::Error:
       ERROR:  current transaction is aborted, commands ignored until end of transaction block

I can call this method with a script many times back-to back, and it works well. I'm also using upsert elsewhere without an issue. Also, all rows are successfully loaded in the database in all cases except for the test. Not sure if this is an Upsert issue or user error, but any insight is much appreciated!

**Comment by evadne** [comment]
This might have been fixed with our earlier thread-safety patch.

**Comment by evadne** [comment]
I ran into a similar situation today and found the following quite useful

    SELECT relation::regclass, * FROM pg_locks WHERE NOT granted;

The culprit was a lock held on one of the tables due to schema creation within a transaction.

I worked around that problem with the following structure.

    RSpec.feature('IBIS Import', type: :feature) {
      self.use_transactional_fixtures = false
      before(:each) {
        Rake::Task['data:inbound:install:medium'].invoke
        ActiveRecord::Base.connection.begin_transaction
      }
      after(:each) {
        ActiveRecord::Base.connection.rollback_transaction
        Rake::Task['data:inbound:install:base'].invoke
      }
      …
    }

**Comment by Ch4s3** [comment]
Is there another fix for this?
