### ISSUE TITLE
Making columns to be ignored on update a configuration

### ISSUE THREAD

**Issue by jpcamara** [seamusabshere/upsert#30]
It's nice that created_at and created_on are being ignored on updates, but it'd be even nicer if it could be expanded to encompass a user specified list of columns :smile: 

Has any thought been put into this before? I have some fields that are required on insert, but don't need to be continually updated past that point (and don't change after insertion).

**Comment by pnomolos** [comment]
This is earlier, but a dup of #51 and since the conversation's there I'm closing this :)
