### ISSUE TITLE
PG Segmentation fault (sidekiq / postgres)

### ISSUE THREAD

**Issue by didil** [seamusabshere/upsert#37]
using upsert 2.0.3 with sidekiq 2.17.7 I get the following error

upsert-2.0.3/lib/upsert/connection/PG_Connection.rb:10: [BUG] Segmentation fault
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0048 p:---- s:0210 e:000209 CFUNC  :exec
c:0047 p:0025 s:0205 e:000204 METHOD /home/didil/.rvm/gems/ruby-2.0.0-p451@project/gems/upsert-2.0.3/lib/upsert/connection/PG_Connection.rb:10
c:0046 p:0080 s:0200 E:001588 METHOD /home/didil/.rvm/gems/ruby-2.0.0-p451@project/gems/upsert-2.0.3/lib/upsert/merge_function/PG_Connection.rb:21
c:0045 p:0021 s:0193 e:000192 METHOD /home/didil/.rvm/gems/ruby-2.0.0-p451@project/gems/upsert-2.0.3/lib/upsert/merge_function.rb:13
c:0044 p:0032 s:0187 e:000186 METHOD /home/didil/.rvm/gems/ruby-2.0.0-p451@project/gems/upsert-2.0.3/lib/upsert.rb:216

**Comment by whistlerbrk** [comment]
@seamusabshere I'm experiencing this as well and will try the solution outlined and report back.

**Comment by seamusabshere** [comment]
@whistlerbrk mysql or postgres?

**Comment by whistlerbrk** [comment]
@seamusabshere postgres

ruby 2.1.5

pg (0.17.1)
rails 4.2.0
sidekiq 3.3.0
hiredis (0.5.2)
redis (3.2.0)

**Comment by whistlerbrk** [comment]
I will add this error did crop up for me when fibers started having to wait for AR connections to become available -- I had concurrency set to be the same as the number of workers.. so I'm not entirely certain why this is occurring, perhaps connections aren't being checked back in, perhaps that is occurring when a job fails. Frankly my setup is really complicated and I neglected to mention I'm also using the makara gem ( https://github.com/taskrabbit/makara ) going to see if there is anything mentioned there about thread safety concerns...

**Comment by matthargett** [comment]
Just so other people hitting this know, we ended up migrating our schema to a format that made upsert unnecessary. We never did work around the reported error.

**Comment by wcurtis** [comment]
I'm hitting a similar error using upsert with sidekiq. Problem dissapears if I set sidekiq concurrency to 1. If I comment out the upsert lines the issue disappears too.

@thbar's solution didn't fix, though I feel like that's the right idea. @whistlerbrk any luck?

**Comment by wcurtis** [comment]
Here's a work-around I'm using in hopes that it helps anyone who finds this issue

Create an `UpsertDataWorker` worker that has its own `upsert` queue
```ruby
class UpsertDataWorker
  include Sidekiq::Worker
  sidekiq_options :queue => :upsert

  def perform upsert_data
    # Upsert the data since this worker process only has one thread :)
  end
end
```
Have a dedicated process with **1 thread** that pulls data off this queue and upserts it
```
bundle exec sidekiq -q upsert -c 1
```

From your multi-threaded workers (which upsert would break) rather than upserting inline, call the upsert worker to perform later
```ruby
# Note: Make sure array_of_data_to_upsert is primitive json so redis accepts it
UpsertDataWorker.perform_async(array_of_json_data_to_upsert)
```

**Caveat:** The queued data must be valid json so redis can store it

Really hoping this gets fixed, but in the mean time if you need upserts and multi-threaded workers then here's a decent option I'm currently running in prod.

**Comment by j0rd** [comment]
Same problem.
```
   Upsert.batch(Product.connection, Product.table_name) do |upsert|                                                                                                                        
      @products.each do |product|                                                                                                                                                           
        puts "Upsert Product #{product.id}"                                                                                                                                                 
        upsert.row({:_id => product.id},                                                                                                                                                    
          :shop_id => shop.id,                                                                                                                                                              
        )
     end
  end
```

Tried adding 
```
ActiveRecord::Base.connection_pool.with_connection do |connection|
```
wrapper around it, but that doesn't fix. I got a full stack dump doing that, where previously it would just segfault with minimal errors.

I'm using Postgres on Rails 4.x & Ruby 2.2.0p0 on linux. Upsert 2.0.4

Turning sidekiq to 1 thread works. Multiple fails.

**Comment by evadne** [comment]
The following code block stops making progress in a couple seconds in our Rails runner (development environment). I also suspect some connection is being reused and this is causing a lockup…

    Upsert.logger = nil
    threads = 10.times.map { |x|
    	Thread.new {
    		ActiveRecord::Base.connection_pool.with_connection { |c|
    		  Upsert.batch(c, :students) { |upsert|
    				loop {
    					Thread.current[:iterations] = 1 + (Thread.current[:iterations] || 0)
    		      upsert.row({ id: '10c273b5-4803-4af7-8149-284feb433d56' }, { gender: 0 })
    				}
    		  }
    		}
    	}
    }

    loop {
    	puts threads.map { |x| x[:iterations] }.inspect
      sleep(1)
    }

**Comment by thbar** [comment]
@evadne indeed the connection is cached and this is what is causing those issues. I started some work here https://github.com/seamusabshere/upsert/pull/44 to refactor and avoid that, but unfortunately I could not go further. I have switched to another solution for my client's project for now.

**Comment by evadne** [comment]
Turns out that Upsert::MergeFunction#connection is reusing the connection from `controller`.

**Comment by evadne** [comment]
I think moving the cache into the upsert instance (instead of doing it on the connection class) will do without affecting performance too much
