### ISSUE TITLE
BUG: UTF8

### ISSUE THREAD

**Issue by stAndrei** [seamusabshere/upsert#49]
After updating records with upsert all russian names become ????? ?????. In upsert log everything fine 

```
[2015-04-08T13:13:09.837068 #3363] DEBUG -- : [upsert] CALL upsert2_1_0_users_SEL_id_SET_balance_A_credit_A_curre4278482623(46085, 11900.03, 0.0, 'USD',  'Валерий Франков').
```

I use MYSQL, mysql2 adapter and Upsert.batch. Column CHAR(128) with encoding UTF-8. Simple insert writes correct.

**Comment by seamusabshere** [comment]
@stAndrei do you have any idea why that happens?

**Comment by stAndrei** [comment]
@seamusabshere, no, I don't.

**Comment by pnomolos** [comment]
@stAndrei I don't know if you're still dealing with this issue, but did you check the character set and encoding values on both sides (client and server)?  I just added a pull request to make sure UTF8 is checked in the tests, but it required a bit of tweaking to make sure everything properly worked on mysql.

**Comment by pnomolos** [comment]
@stAndrei I've added a spec to verify that this isn't an Upsert issue in PR #86 .  Do note that if you were using MySQL's `utf8` charset (as opposed to `utf8mb4`) it's possible you're running into issues with that charset.
