### ISSUE TITLE
Slower than AR?

### ISSUE THREAD

**Issue by nilcolor** [seamusabshere/upsert#59]
Hi!
I try to use this gem and there is something I can not understand...

``` ruby
# using upsert gem
# >>>>>> finished in 382.501348 sec <<<<<<<
now = Time.zone.now.utc
Upsert.batch(Certificate.connection, Certificate.table_name) do |upsert|
  CSV.foreach(@file, CSV_OPTIONS) do |row|
    selector = { part_number: row[1].tr("'", ""), manufacturer: row[4] }
    fields = { date: Date.strptime(row[0], "%d-%b-%y"),
               number: row[2],
               note: row[3],
               address: row[5],
               created_at: now,
               updated_at: now }
    upsert.row(selector, fields)
  end
end
```

while

``` ruby
# AR
# >>>>>> finished in 210.520644 sec <<<<<<<
CSV.foreach(@file, CSV_OPTIONS) do |row|
  params = { date: Date.strptime(row[0], "%d-%b-%y"),
             part_number: row[1].tr("'", ""),
             number: row[2],
             note: row[3],
             manufacturer: row[4],
             address: row[5] }
  Certificate
    .find_or_initialize_by(part_number: params[:part_number], manufacturer: params[:manufacturer]) do |m|
      m.assign_attributes params
    end
    .tap do |m|
      if m.persisted?
        m.update_columns(params.slice(:date, :number, :note, :address))
      else
        m.save!(validate: false)
      end
    end
end
```

Am I miss something? I'm using PG 9.3 btw.
File I was loading - is about 32k lines. When I use it to load small amount of records (about 100 lines) upsert was fastest. But not with real csv.

P.S.
Rails 4.0.13

**Comment by jufemaiz** [comment]
Wow. I'm interested in these benchmarks!

**Comment by pnomolos** [comment]
@nilcolor Are you still interested in this?  If you wouldn't mind re-testing with the latest version of the gem to verify you're still seeing the performance issue, that would be great.  If it's still an issue after that is there a chance I could get some sample data from you to test against?

**Comment by nilcolor** [comment]
@pnomolos I'm really sorry but I'm not working on that project since 2016. So it can be difficult to repeat the test.
If I will have an opportunity to use this gem in my current work I'll let you know how its going.
Thank you for your work!
I think we can close this ticket for now.

**Comment by pnomolos** [comment]
Closing this issue for now.  @nilcolor If you run into an issue again please open a new ticket 👍
