### ISSUE TITLE
PostgreSQL + JDBC: Error when updating value of a BIGINT column

### ISSUE THREAD

**Issue by avivrosenberg** [seamusabshere/upsert#61]
Hi,
I'm using Upsert (2.0.3) with JRuby 9.0.1.0 and PostgreSQL 9.3.

I have the following code:

``` ruby
Upsert.batch(MWMT::DAL.connection, table_name) do |upsert|
  node_data.each do |node_merge_data|
    upsert.row({node_id: node_merge_data[:node_id]}, pressure: node_merge_data[:pressure], merge_count: node_merge_data[:count])
  end
end
```

Which updates rows on the following table:

```
      Column      |         Type         |     Modifiers
------------------+----------------------+--------------------
 node_id          | bigint               | not null
 pressure_version | integer              | default 0
 merge_count      | smallint             | not null default 0
    .
    .
    .
```

This code used to work fine before I moved my application to JRuby. Now, with JRuby, I get the following error exception:

```
#<RangeError: too big for int: 3599657714>
```

This number (3599657714) is the value of the `node_id` column of the row being updated.

Here is the relevant part of the stacktrace:

```
[ 0] "/Users/aviv/.rvm/gems/jruby-9.0.1.0@mwmt/gems/upsert-2.0.3/lib/upsert/connection/jdbc.rb:47:in `block in execute'",
[ 1] "org/jruby/RubyArray.java:1560:in `each'",
[ 2] "org/jruby/RubyEnumerable.java:1016:in `each_with_index'",
[ 3] "/Users/aviv/.rvm/gems/jruby-9.0.1.0@mwmt/gems/upsert-2.0.3/lib/upsert/connection/jdbc.rb:36:in `execute'",
[ 4] "/Users/aviv/.rvm/gems/jruby-9.0.1.0@mwmt/gems/upsert-2.0.3/lib/upsert/merge_function/Java_OrgPostgresqlJdbc4_Jdbc4Connection.rb:18:in `execute'",
[ 5] "/Users/aviv/.rvm/gems/jruby-9.0.1.0@mwmt/gems/upsert-2.0.3/lib/upsert/merge_function.rb:13:in `execute'",
[ 6] "/Users/aviv/.rvm/gems/jruby-9.0.1.0@mwmt/gems/upsert-2.0.3/lib/upsert.rb:216:in `row'",
[ 7] "/Users/aviv/dev/mobiwize/mw-server/mw-maptools/lib/mw-maptools/data_layer.rb:357:in `block in persist_node_data'",
```

Looking at the Upsert code where the error originates, I saw the following:

``` java
setter = setters[v.class.name]
statement.send setter, i+1, v
```

Since the value `v` is a ruby `Fixnum`, the setter that is found for it is `setInt`.
However, since the number is very large, it can't be converted to int.
I think that the correct method to invoke on the statement in this case would be `setLong`.

I might be missing something and not using Upsert correctly, but it does seem that updating `BIGINT` columns is currently not supported.

Thanks for your help!

**Comment by pnomolos** [comment]
@avivrosenberg A fix for this should be coming via https://github.com/seamusabshere/upsert/pull/80.  If you're able to test that branch against your code and see if it works for you that would be great :)
