### ISSUE TITLE
Procedure re-created on every use

### ISSUE THREAD

**Issue by santervo** [seamusabshere/upsert#62]
I'm using upsert rails plugin (ModelName.upsert(...))

Every time I call upsert method on rails plugin, I see new log entry

    Creating or replacing database function "upsert2_1_0....

Procedure name is same but it's still re-created on *every* call. Is this bug or intentional?

Github page says that is should re-use existing function. ("Transparently creates (and re-uses) stored procedures/functions when necessary")

**Comment by santervo** [comment]
I assume this happens because new Upsert object along with new MergeFunction object are created on every call to ActiveRecordModel.upsert. In the MergeFunction constructor procedure is created:

     create! unless assume_function_exists

**Comment by seamusabshere** [comment]
@santervo it looks like this happens because of https://github.com/seamusabshere/upsert/commit/e3e85941d7cd024c8f598ce3c431db4f3cc93fdd

@evadne do you have any ideas on how we can prevent every call to `Pet.upsert` from recreating the function every time?

**Comment by randomm** [comment]
This is also an issue for us, my log files are full of this...
```
Creating or replacing database function "upsert2_1_0....
```

**Comment by santervo** [comment]
@seamusabshere @evadne 

If I understand correctly, upsert will still recreate procedure if it does not exist (at least with MySQL)

https://github.com/seamusabshere/upsert/blob/master/lib/upsert/merge_function/Mysql2_Client.rb#L19

One option would be to allow defining "assume_function_exists" default value in some global configuration (during app initialisation)

**Comment by evadne** [comment]
Looks like a MySQL-only problem?

**Comment by randomm** [comment]
Happens with Postgres also.

**Comment by seamusabshere** [comment]
@evadne would it be possible to avoid this by simply defaulting `assume_function_exists` to true?

**Comment by seamusabshere** [comment]
possibly fixed by https://github.com/seamusabshere/upsert/commit/daef036ab28258b977ada5d4de790cd32b26b064
