### ISSUE TITLE
bug(postgres): possible to cause a PG::AmbiguousFunction exception

### ISSUE THREAD

**Issue by evadne** [seamusabshere/upsert#68]
I got the following exceptions being thrown a couple of times in Postgres when I kick off a few thousand concurrent Sidekiq jobs that use Upsert.

```
PG::AmbiguousFunction: ERROR: function upsert2_1_0_portfolio_status_cache_entries_sel_portfo1447696404(unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown) is not uniqueLINE 1: SELECT upsert2_1_0_portfolio_status_cache_entries_SEL_portfo... ^HINT: Could not choose a best candidate function. You might need to add explicit type casts.
```

This particular exception is thrown here:

```
lib/upsert/connection/PG_Connection.rb: 10:in `exec'
lib/upsert/connection/PG_Connection.rb: 10:in `execute'
lib/upsert/merge_function/PG_Connection.rb: 21:in `execute'
lib/upsert.rb: 218:in `row'
```

Upon further investigation with the following query things look fine, all Upsert functions appear exactly once in the `public` schema:

```
with procs as (select proname, pronamespace from pg_proc where proowner <> 1 and proname like 'upsert%' order by proname asc) select procs.*, pg_namespace.nspname from procs left join pg_namespace on pg_namespace.oid = procs.pronamespace;
```

I have two separate concerns regarding this finding.
1. The `CREATE OR REPLACE FUNCTION` call has the function name prefixed with `Upsert::MergeFunction::NAME_PREFIX` which is a version tag. Should the Upsert functions always be created in a specific schema?
2. I’m still wondering what are the possible scenarios that cause the Upsert functions to become ambiguous?

**Comment by pnomolos** [comment]
@evadne Is this still happening?  It looks like the problem is that Upsert isn't passing any type information when it calls the function, so PostgreSQL can't figure out which one to call.

**Comment by pnomolos** [comment]
I'm marking this as closed for now, no response.
