### ISSUE TITLE
uses a different merge function for every combination of inputs

### ISSUE THREAD

**Issue by seamusabshere** [seamusabshere/upsert#71]
it should just have a single postgres function that takes one selector arg and one setter arg

the arg type should be `record` or maybe `hstore` or maybe `json`

then we don't have to constantly create new merge functions for new inputs

**Comment by seamusabshere** [comment]
@evadne i think this would solve a large number of problems

it would also make the approach competitive even with 9.5 UPSERT because we don't require unique keys

**Comment by evadne** [comment]
@seamusabshere a couple of questions

1. Do we need to marshal / unmarshal and does that hurt performance
2. Is it bad if we rely on Postgres 9.5 UPSERT?

**Comment by seamusabshere** [comment]
@evadne 

1. i checked in the #postgresql IRC channel and apparently you can't use `record` as an input type. that makes me think we have to pass in json (e.g., `upsert(selector::jsonb, setter::jsonb)`) in order to allow many different inputs to use the same function. there will be a performance penalty, but it will still be faster (i think) than the alternatives (except of course native 9.5 upsert, but see below).
2. 9.5's upsert is actually not equivalent... it requires you to have a unique index and runs the update only if there is a duplicate key error. also, most people don't have 9.5 (as of this writing it's not even available on Amazon RDS)

**Comment by seamusabshere** [comment]
i think this is basically impossible - we have to write an upsert function for every combo of inputs.
