### ISSUE TITLE
PostgreSQL error » duplicate key value violates unique constraint "pg_proc_proname_args_nsp_index"

### ISSUE THREAD

**Issue by jufemaiz** [seamusabshere/upsert#72]
``` SQL
ERROR:  duplicate key value violates unique constraint "pg_proc_proname_args_nsp_index"
DETAIL:  Key (proname, proargtypes, pronamespace)=(upsert2_1_0_measurement_data_sel_measurement_point_id2088041071, 23 1043 1043 23 1043 701, 2200) already exists.

/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert/connection/PG_Connection.rb:13:in `exec'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert/connection/PG_Connection.rb:13:in `execute'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert/merge_function/postgresql.rb:106:in `create!'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert/merge_function.rb:39:in `initialize'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert.rb:229:in `new'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert.rb:229:in `merge_function'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert.rb:218:in `row'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert/active_record_upsert.rb:6:in `block in upsert'
/var/app/current/vendor/bundle/ruby/2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/app/current/vendor/bundle/ruby/2.0/gems/upsert-2.1.0/lib/upsert/active_record_upsert.rb:4:in `upsert'
…
```

I'm using upsert as part of a background process (Delayed::Job) dealing with inbound data on PostgreSQL with a number of processors.

PostgreSQL shows the following: http://www.postgresql.org/message-id/4B9EA2FD.8090902@agliodbs.com

**Comment by jufemaiz** [comment]
Just wondering if there was any thoughts on this one?

**Comment by pnomolos** [comment]
@jufemaiz Any chance you could provide a code sample (if you're still running into the issue)?

**Comment by jufemaiz** [comment]
Hi @pnomolos, I've rolled off to an alternative solution using composite primary keys + create_or_update_value

https://gist.github.com/jufemaiz/6043806705eb4fb906f53468c50c7480

That's approximating what I'm trying to achieve.

Multiple application instances doing this concurrently on different data sets.

**Comment by pnomolos** [comment]
@jufemaiz Are you wrapping your upsert blocks in transactgions?

**Comment by pnomolos** [comment]
@jufemaiz Also, is/was your code multi-threaded, or is/was it independent delayed jobs causing the issues?

**Comment by jufemaiz** [comment]
@pnomolos you'll have to go easy on me, going back a bit.

1. Not that I remember.
2. Independent jobs were causing issues (I believe). I had multiple Delayed::Job processes running in parallel, on multiple instances (AWS EC2).

**Comment by pnomolos** [comment]
@jufemaiz If you're willing/able to try this again once the next version of the gem comes out, that would be great.  Also, wrapping your Upsert block in a transaction (not sure if that's feasible for your use case) should help guard against this.  It looks like two independent jobs are both checking for the existence of a function at the same time, then both trying to create it.  As well, if you're using PG 9.5+ none of this should be an issue as the new `INSERT ... ON CONFLICT` syntax will be used :)
