### ISSUE TITLE
Old stored procedure not updated

### ISSUE THREAD

**Issue by Ch4s3** [seamusabshere/upsert#76]
I have a column that was changed from integer to float and the stored procedure keeps reverting to the integer type and breaking on insert with the following error:

```
PG::InvalidTextRepresentationapp/models/concerns/upsertable.rb:15
ERROR: invalid input syntax for integer: 
```

I've tried dropping the database and recreating it to regenerate new procedures and then committing those. It still breaks on my staging environment as though the procedures are being restored or recreated incorrectly.

**Comment by pnomolos** [comment]
@Ch4s3 If you run something like the following you can clear all currently existing functions created by upsert:

```ruby
    Upsert::MergeFunction::NAME_PREFIX = "upsert"
    # Following example is for Sequel, replace it with 
    # whatever you need to get a direct connection in your app
    DB.synchronize do |conn|
      Upsert.clear_database_functions(conn)
    end
```

I have a rake task that is run after deployment so fresh versions of the functions are available every time.
