### ISSUE TITLE
installation on rails?

### ISSUE THREAD

**Issue by BKSpurgeon** [seamusabshere/upsert#93]
Hi all

thank you so much for the hard work you've put into this.

pls forgive my ignorance. how do i actually get this gem this to installed on a rails app? there were no explicit instructions on the documentation and am seeking your advice. pointers much appreciated. chrs

regards

Ben

**Comment by pnomolos** [comment]
Hi Ben,

All you need to do is add `gem "upsert"` to your Gemfile and run `bundle install`.  There are no installation instructions other than that.  Usage is as mentioned in the README; https://github.com/seamusabshere/upsert#activerecord-helper-method probably would be the most likely method for you to use.

**Comment by BKSpurgeon** [comment]
Hello thx so much.
