### ISSUE TITLE
Doesn't work on heroku

### ISSUE THREAD

**Issue by letronje** [seamusabshere/upsert#96]
The upsert calls work locally, but on Heroku, I see this error

LINE 1: SELECT upsert2_1_2_group_conversations_SEL_id_SET_id_A_lates...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by pnomolos** [comment]
@letronje Are you able to log in to a psql shell on heroku and try creating a function yourself?  I took a look over the code again and while it __should__ throw an error (from Upsert, not PG) if the function creation fails, perhaps there's an edge-case that's been missed.

**Comment by seamusabshere** [comment]
@letronje can you provide a fuller backtrace?

**Comment by letronje** [comment]
Hey sorry about the delay. I think restarting the dyno helped. works now.
