### ISSUE TITLE
Release plan?

### ISSUE THREAD

**Issue by willsoto** [seamusabshere/upsert#97]
Thank you for creating this library, it's great!

I have a question about releases. There hasn't been a release in some time, and I was wondering if there are any plans to do so? It would be great to have #79 without having to reference the latest commit hash.

Is there anything we can do to help this process?

Thanks!

**Comment by pnomolos** [comment]
@willsoto funny this should come up today - Seamus just released 2.2.0 which includes all those fixes!  I'm hoping we can push out releases more often in future, though :)

**Comment by willsoto** [comment]
Thank you so much!
