### ISSUE TITLE
Clarification on unique indexes

### ISSUE THREAD

**Issue by willsoto** [seamusabshere/upsert#98]
I noticed [this](https://github.com/seamusabshere/upsert#native-postgres-upsert) in the README, but I think I need some clarification on what it means.

Currently, I am seeing the non-native `upsert` being used even though I have am on Postgres 9.6 and I have a unique index on the field I am upserting on.

```
> show server_version
+------------------+
| server_version   |
|------------------|
| 9.6.2            |
+------------------+
SHOW
Time: 0.001s
```

I am on version 2.2.0 of the gem, from `Gemfile.lock`:

```
upsert (2.2.0)
```

Any thoughts or clarification would be helpful here, thank you.

**Comment by pnomolos** [comment]
@willsoto Do you mind posting the output of `\d+ <table_name>`, as well as the Upsert snippet that you're using?

**Comment by willsoto** [comment]
I can post a snippet of that table - unfortunately I can't post the whole thing.

```
+------------+-----------------------------+-----------------------------------------------------+
| Column     | Type                        | Modifiers                                           |
|------------+-----------------------------+-----------------------------------------------------|
| id         | integer                     |  not null default nextval('users_id_seq'::regclass) |
| handle     | character varying           |  not null                                           |
| token      | character varying           |                                                     |
+------------+-----------------------------+-----------------------------------------------------+
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "index_users_on_handle" UNIQUE, btree (handle)
    "index_users_on_token" UNIQUE, btree (token)
```

And here is the code:

```ruby
User.upsert({ :handle => handle }, params.merge(created_at: Time.current, updated_at: Time.current))
```

I am using AR as well. I have `require 'upsert/active_record_upsert'` in the `application.rb`

**Comment by pnomolos** [comment]
@willsoto Can you post the results of the following query (omitting what you have to)?

```sql
            SELECT array_agg(column_name::text) AS index_columns FROM information_schema.constraint_column_usage
              JOIN pg_catalog.pg_constraint ON constraint_name::text = conname::text
              WHERE table_name = $1 AND conrelid = $1::regclass::oid AND contype = 'u'
              GROUP BY table_catalog, table_name, constraint_name
```

Replace `$` with your quoted table name.

**Comment by willsoto** [comment]
So I _think_ I did it right. 

Here is the query:

```sql
SELECT array_agg(COLUMN_NAME::text) AS index_columns
FROM information_schema.constraint_column_usage
JOIN pg_catalog.pg_constraint ON CONSTRAINT_NAME::text = conname::text
WHERE TABLE_NAME = 'users'
  AND conrelid = '"users"'::regclass::oid
  AND contype = 'u'
GROUP BY table_catalog,
         TABLE_NAME,
         CONSTRAINT_NAME
```

Here is the output:

```
+-----------------+
| index_columns   |
|-----------------|
+-----------------+
SELECT 0
Time: 0.005s
```

**Comment by pnomolos** [comment]
@willsoto OK, I may have to see if I can make this a little better.  It looks like you only have a unique index, which isn't classed as a constraint in Postgres.  A unique constraint will create an index, but not vice-versa.  However, if you try the following:

```sql
ALTER TABLE users
    ADD CONSTRAINT users_constraint_on_handle UNIQUE USING INDEX index_users_on_handle;
```

I believe that will get you what you want.

**Comment by willsoto** [comment]
Alright, so that makes sense now, I didn't even think to take a look if AR was adding a true `CONSTRAINT`...

```
> SELECT array_agg(COLUMN_NAME::text) AS index_columns
..................... FROM information_schema.constraint_column_usage
..................... JOIN pg_catalog.pg_constraint ON CONSTRAINT_NAME::text = conname::text
..................... WHERE TABLE_NAME = 'users'
.....................   AND conrelid = '"users"'::regclass::oid
.....................   AND contype = 'u'
..................... GROUP BY table_catalog,
.....................          TABLE_NAME,
.....................          CONSTRAINT_NAME
+-----------------+
| index_columns   |
|-----------------|
| [u'handle']     |
+-----------------+
SELECT 1
Time: 0.007s
```

I get a new error now though:

```
NoMethodError (undefined method `sort' for "{handle}":String):
```

Any thoughts?

**Comment by pnomolos** [comment]
Hi Will,

Yes, I saw that error as well when I was debugging your problem.  I _believe_ that the `pg` library may have changed things and this is why it isn't working.  I'll get a PR and patch together hopefully soon, but for the meantime including this code somewhere after Upsert is required this should do the trick for you:

```ruby
class Upsert
  class MergeFunction
    class PG_Connection < MergeFunction
      def unique_index_on_selector?
        return @unique_index_on_selector if defined?(@unique_index_on_selector)

        type_map = PG::TypeMapByColumn.new([PG::TextDecoder::Array.new])
        res = schema_query.tap { |r| r.type_map = type_map }

        @unique_index_on_selector = res.values.any? do |row|
          row.first.sort == selector_keys.sort
        end
      end
    end
  end
end
```

**Comment by willsoto** [comment]
Still seeing the same error. I am adding that snippet of code in an initializer. I've tried it several ways with no luck. Not sure if it has anything to do with the fact that I am using ActiveRecord?

**Comment by pnomolos** [comment]
@willsoto No, I don't believe so.  I'm not able to test right now, but now that I think about it harder I believe that Upsert loads the adapters dynamically on the first Upsert call, so your code would always be overridden (unless you wanted to go through the trouble of calling Upsert one, catching the error, then inserting your code).  As I said, I'll try and put a test case together and a patch.  If you want to try editing the gem directly, the code is found in `lib/upsert/merge_function/PG_Connection.rb`

**Comment by pnomolos** [comment]
@willsoto Once #99 is passing I'll see if @seamusabshere Can bump the version to 2.2.1 and cut us a new gem!

**Comment by willsoto** [comment]
Thank you for such a timely resolution. I appreciate it.

**Comment by seamusabshere** [comment]
hopefully fixed by https://github.com/seamusabshere/upsert/commit/5e32c94917e4697bba591a87639c947e92ad3423

**Comment by willsoto** [comment]
That did it. Thanks again for everything.
